project:
  type: website

website:
  title: "Igor B. Martins"
  navbar:
    left:
      - text: Home
        href: "#home"
      - text: About
        href: "#about-me"
      - text: Works
        href: "#selected-works"
      - text: Teaching
        href: "#teaching"
      - text: Contact
        href: "#contact"

format:
  html:
    theme:
      light:
        primary:    "#B20086"
        secondary:  "#333333"
        background: "#F5F5F5"
        body-font:  "Lora"
        heading-font: "Montserrat"
        mono-font:  "Source Code Pro"
      dark:
        primary:    "#B20086"
        secondary:  "#EEEEEE"
        background: "#222222"
        body-font:  "Lora"
        heading-font: "Montserrat"
        mono-font:  "Source Code Pro"
    code-fold: true
    highlight-style: tango
    css: styles.scss
    toc: false

