project:
  type: website

website:
  title: "Igor B. Martins"
  navbar:
    left:
      - text: Home
        href: "#home"
      - text: About
        href: "#about-me"
      - text: Works
        href: "#selected-works"
      - text: Teaching
        href: "#teaching"
      - text: Contact
        href: "#contact"

format:
  html:
    theme:
      light: cosmo
      dark: cosmo
    primary:    "#B20086"           # accent color
    secondary:  "#333333"           # main text color
    background: "#F5F5F5"           # page background
    body-font:  "Lora"              # serif body
    heading-font: "Montserrat"      # sans headings
    mono-font:  "Source Code Pro"
    code-fold: true
    highlight-style: tango
    css: styles.scss
    toc: false
